# Generated by Django 3.2.1 on 2021-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
    ]
