# Generated by Django 3.2.1 on 2021-05-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_products_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
    ]
