# Generated by Django 3.2.1 on 2021-05-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_products_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_tab',
            field=models.BooleanField(default=False),
        ),
    ]
