# Generated by Django 3.2.1 on 2021-05-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_products_is_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
