# Generated by Django 3.2.1 on 2021-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_products_is_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='')),
                ('discount', models.BooleanField(default=False)),
                ('discounted_price', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_tab', models.BooleanField(default=False)),
            ],
        ),
    ]
