# Generated by Django 3.2.1 on 2021-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tabs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabs',
            old_name='is_trending',
            new_name='is_main_img',
        ),
    ]
