# Generated by Django 3.2.1 on 2021-05-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210524_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabs',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_mobile',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_tab',
        ),
    ]
