# Generated by Django 3.2.1 on 2021-06-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_pdctimgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='categories',
        ),
        migrations.AddField(
            model_name='categories',
            name='brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.brands'),
        ),
    ]
