# Generated by Django 3.2.1 on 2021-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout_cart',
            name='product',
        ),
        migrations.AddField(
            model_name='checkout_cart',
            name='product',
            field=models.ManyToManyField(to='myapp.Products'),
        ),
    ]
