# Generated by Django 3.2.1 on 2021-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_checkout_cart_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('product', models.ManyToManyField(to='myapp.Products')),
            ],
        ),
        migrations.DeleteModel(
            name='checkout_cart',
        ),
    ]
