# Generated by Django 3.2.1 on 2021-06-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210616_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('area_code', models.IntegerField(default=0)),
                ('phone_num', models.IntegerField(default=0)),
                ('street_address', models.TextField()),
                ('zip_code', models.IntegerField(default=0)),
                ('buisness_address', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_total_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('checkout_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
