# Generated by Django 3.2.1 on 2021-06-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20210618_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='buisness_address',
            field=models.BooleanField(default=False),
        ),
    ]
