# Generated by Django 3.2.1 on 2021-06-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_order_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='buisness_address',
        ),
    ]
